apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: toggla-service
    app.kubernetes.io/name: toggla-service
    app.kubernetes.io/part-of: toggla
  name: toggla-service
spec:
  replicas: 1
  selector:
    app: toggla-service
  template:
    metadata:
      labels:
        app: toggla-service
    spec:
      containers:
        - command:
            - java
            - -Dquarkus.http.host=0.0.0.0
            - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            - -jar
            - /deployments/quarkus-run.jar
          image: default/toggla-service:latest
          imagePullPolicy: Always
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
          name: toggla-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
  triggers:
    - type: ConfigChange
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  generation: 1
  labels:
    app: toggla-web
    app.kubernetes.io/name: toggla-web
    app.kubernetes.io/part-of: toggla
  name: toggla-web
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: toggla-web
    deploymentconfig: toggla-web
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: toggla-web
        deploymentconfig: toggla-web
    spec:
      containers:
        - image: default/toggla-web:latest
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - "-c"
                  - >-
                    for f in $(find /opt/app-root/src -regex '.*main.*\.js'); do
                    envsubst "$(printenv | grep ENV | cut -d'=' -f1 | awk
                    '{print "$" $0}' | paste -sd " ")" < $f > $f.tmp; cp $f.tmp
                    $f ;done
          name: toggla-web
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/opt/rh/rh-nginx112/nginx/
              name: nginx-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGraceperiodSeconds: 10
      volumes:
        - name: nginx-config
          configMap:
            defaultMode: 420
            name: toggla-web-nginx-config
  test: false
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: toggla-redis-datasource
    app.kubernetes.io/name: toggla-redis-datasource
    app.kubernetes.io/part-of: toggla
  name: toggla-redis-datasource
spec:
  replicas: 1
  selector:
    app: toggla-redis-datasource
  template:
    metadata:
      labels:
        app: toggla-redis-datasource
    spec:
      containers:
        - name: toggla-redis-datasource
          image: redis
          command:
            - redis-server
            - "/redis-master/redis.conf"
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
            - mountPath: /redis-master
              name: config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: toggla-redis-datasource-volume-claim
        - name: config
          configMap:
            name: toggla-redis-datasource-config
            items:
              - key: redis-config
                path: redis.conf
            defaultMode: 420
