apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: toggler-redis-datasource-volume-claim
spec:
  storageClassName: vsan
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
