apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: toggla-redis-datasource-volume-claim
  labels:
    app.kubernetes.io/part-of: toggla
spec:
  storageClassName: vsan
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
