apiVersion: v1
kind: ConfigMap
metadata:
  name: toggler-redis-datasource-config
  labels:
    app.kubernetes.io/part-of: toggler
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
