apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/part-of: toggla
    app: toggla-web
  name: toggla-web
spec:
  host: toggla.se
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  to:
    kind: Service
    name: toggla-web
    weight: 100
  wildcardPolicy: None

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/part-of: toggla
    app: toggla-service
  name: toggla-service
spec:
  host: toggla-service.se
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: Service
    name: toggla-service
    weight: 100
  wildcardPolicy: None
