apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: toggla
    app: toggla-service
  name: toggla-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: toggla-service
    deploymentconfig: toggla-service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: toggla
    app: toggla-web
  name: toggla-web
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: toggla-web
    deploymentconfig: toggla-web
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: toggla-redis-datasource
  labels:
    app.kubernetes.io/part-of: toggla
    app: toggla-redis-datasource
spec:
  type: ClusterIP
  selector:
    app: toggla-redis-datasource
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
