AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Resources:
  Toggla:
    FunctionName: !Sub toggla-service_${AWS::Region}
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      Handler: not.used.in.provided.runtime
      Runtime: provided.al2
      CodeUri: ../../toggla-service/target/function.zip
      MemorySize: 256
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Timeout: 15
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
      Events:
        HttpApiEvent:
          Type: HttpApi

Outputs:
  TogglaApi:
    Description: URL for application
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
    Export:
      Name: TogglaApi
