kind: PersistentVolume
apiVersion: v1
metadata:
  name: toggler-redis-datasource-volume
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"