apiVersion: v1
kind: Service
metadata:
  name: toggla-service
  labels:
    app: toggla-service
spec:
  type: NodePort
  selector:
    app: toggla-service
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: toggla-web
  labels:
    app: toggla-web
spec:
  type: NodePort
  selector:
    app: toggla-web
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: toggla-redis-datasource
  labels:
    app: toggla-redis-datasource
spec:
  type: ClusterIP
  selector:
    app: toggla-redis-datasource
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
