name: pull-request

on:
  pull_request:
    branches: [master]

permissions:
  packages: write

concurrency:
  group: pull-request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MVN: mvn --show-version --batch-mode
    steps:
      - name: jdk17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - name: GraalVM 22.1.0
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 17
          version: 22.1.0
          native-image-musl: true
      - name: checkout
        uses: actions/checkout@v2.4.2
        with:
          token: ${{ secrets.PAT }}
      - name: cache ~/.m2
        uses: actions/cache@v3.0.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: mvn clean verify
        working-directory: toggla-service
        run: $MVN clean verify
