name: toggla-service_eu-west

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  packages: write

concurrency:
  group: ci-native

jobs:
  test-native:
    runs-on: ubuntu-latest
    env:
      MVN: mvn --show-version --batch-mode
    steps:
      - name: jdk17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - name: GraalVM 22.1.0
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 17
          version: 22.1.0
          native-image-musl: true
      - name: checkout
        uses: actions/checkout@v2.4.2
      - name: cache ~/.m2
        uses: actions/cache@v3.0.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: mvn clean verify -Pnative
        working-directory: toggla-service
        run: $MVN clean verify -Pnative
  # Image push happens before native tests when running 'mvn clean verify -Pnative -Dquarkus.container-image.push=true', so decided to split.
  build-native:
    if: github.ref == 'refs/heads/master'
    needs: test-native
    runs-on: ubuntu-latest
    env:
      MVN: mvn --show-version --batch-mode
    steps:
      - name: JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          logout: true
      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: checkout
        uses: actions/checkout@v2.4.2
      - name: cache ~/.m2
        uses: actions/cache@v3.0.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: mvn package -Pnative -DskipTests -Dquarkus.native.container-build=true
        working-directory: toggla-service
        run: $MVN package -Pnative -DskipTests -Dquarkus.native.container-build=true
      - name: sam deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset -t deployment/aws/sam.native.yaml --stack-name toggla --s3-bucket artifacts-gamma --capabilities CAPABILITY_IAM
        
